%hidden MODULE_NAME="git"
set -g "@catppuccin_${MODULE_NAME}_icon" " "
set -gF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_green}"
set -g "@catppuccin_${MODULE_NAME}_text" " #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null)"
source -F "#{d:current_file}/plugins/tmux/utils/status_module.conf"
